import type { EquipSlot } from './Inventory';
import type { SkillId } from './Skills';
import type { WeaponType } from './combat';
import { WIKI_ITEMS, WikiBonuses } from './wikiItems';

/**
 * The item config registry — every item the game knows, keyed by id, in the
 * spirit of the obj configs an OSRS server ships. Instances in the world are
 * just `{ id, qty }` stacks ({@link ItemStack}); everything static lives here.
 *
 * Names, examine lines, values, weights, attack speeds, and the full stab /
 * slash / crush / magic / ranged bonus tables come straight from the OSRS
 * Wiki (src/sim/wikiItems.ts, generated by scripts/build-items.mjs). What an
 * item *does* in Aeloria — what it cooks into, which tool tier it is, what
 * level it needs — is defined here by hand.
 */

/** Equipment bonuses, in the order the OSRS equipment screen lists them. */
export type Bonuses = WikiBonuses;

export const ZERO_BONUSES: Bonuses = {
  astab: 0,
  aslash: 0,
  acrush: 0,
  amagic: 0,
  arange: 0,
  dstab: 0,
  dslash: 0,
  dcrush: 0,
  dmagic: 0,
  drange: 0,
  str: 0,
  rstr: 0,
  mdmg: 0,
  prayer: 0,
};

export interface LevelReq {
  readonly skill: SkillId;
  readonly level: number;
}

export interface ItemDef {
  readonly id: string;
  readonly name: string;
  /** Placeholder glyph until real sprites exist. */
  readonly icon: string;
  /** Right-click Examine flavor text. */
  readonly examine: string;
  /** Base value in coins; ranks "items kept on death" and prices shop stock. */
  readonly value: number;
  /** Carried weight — feeds the OSRS run-energy drain formula. */
  readonly weightKg: number;
  /** Stackables occupy one slot at any quantity (coins, runes, bait). */
  readonly stackable?: boolean;

  // --- Equipment ---------------------------------------------------------
  readonly equip?: EquipSlot;
  /** Stat requirements to wear/wield, e.g. rune weapons need 40 Attack. */
  readonly equipReq?: readonly LevelReq[];
  readonly bonuses?: Bonuses;
  /** Weapon attack interval in ticks (scimitar 4, longsword 5, 2h 7…). */
  readonly speed?: number;
  /** Which attack-style set the combat tab shows for this weapon. */
  readonly weaponType?: WeaponType;
  /** Two-handed weapons occupy the shield slot as well. */
  readonly twoHanded?: boolean;
  /** Bows: how many tiles away a target may be (longrange adds two). */
  readonly attackRange?: number;
  /** Staves: the runes this staff supplies without end. */
  readonly staffRunes?: readonly string[];
  /** Ammunition this launcher fires (item id prefix match: "arrow"). */
  readonly ammoKind?: string;
  /** For ammunition: which launcher family fires it. */
  readonly ammoFor?: string;

  // --- Consumables & skilling --------------------------------------------
  /** Hitpoints restored when eaten; presence marks the item as food. */
  readonly heals?: number;
  /** Prayer XP for burying; presence marks the item as bones. */
  readonly buryXp?: number;
  /** Axe/pickaxe power tier (1 bronze … 6 rune); tools, not weapons. */
  readonly axeTier?: number;
  readonly pickTier?: number;
  /** Woodcutting / Mining level needed to *use* the tool (steel axe: 6). */
  readonly toolLevel?: number;
  /** Firemaking: [level, XP] for burning; presence makes "Light" available. */
  readonly firemaking?: { readonly level: number; readonly xp: number };
  /** Cooking: what this raw item becomes, and the curve that governs burning. */
  readonly cooking?: {
    readonly cooked: string;
    readonly burnt: string;
    readonly level: number;
    readonly xp: number;
    /** Cooking level at which this food stops burning on a fire. */
    readonly stopBurn: number;
    /** …and on a kitchen range (the Lumbridge-style range burns less). */
    readonly stopBurnRange?: number;
  };
}

/** A quantity of one item — what actually sits in a slot or on the ground. */
export interface ItemStack {
  readonly id: string;
  qty: number;
}

export function stackOf(id: string, qty = 1): ItemStack {
  return { id, qty };
}

/** Look up an item's config. Throws on unknown ids — those are content bugs. */
export function itemDef(id: string): ItemDef {
  const def = ITEMS[id];
  if (!def) throw new Error(`Unknown item id: ${id}`);
  return def;
}

/** Every item id, for the debug handle and tests. */
export function allItemIds(): string[] {
  return Object.keys(ITEMS);
}

const ITEMS: Record<string, ItemDef> = {};

/** Fields the wiki supplies; anything passed in `extra` overrides them. */
type Extra = Partial<Omit<ItemDef, 'id'>> & { icon: string };

/** Define an item from its wiki record plus game behaviour. */
function wiki(id: string, extra: Extra): void {
  const w = WIKI_ITEMS[id];
  if (!w) throw new Error(`No wiki record for ${id}; run scripts/build-items.mjs`);
  const slot = w.slot ? SLOT_BY_WIKI[w.slot] : undefined;
  ITEMS[id] = {
    id,
    name: w.name,
    examine: w.examine,
    value: w.value,
    weightKg: w.weightKg,
    stackable: w.stackable || undefined,
    equip: slot,
    bonuses: w.bonuses,
    speed: w.speed,
    twoHanded: w.slot === '2h' || undefined,
    ...extra,
  };
}

/** Items the wiki import doesn't cover (or covers under another name). */
function define(def: ItemDef): void {
  ITEMS[def.id] = def;
}

const SLOT_BY_WIKI: Record<string, EquipSlot> = {
  weapon: 'weapon',
  '2h': 'weapon',
  head: 'helmet',
  body: 'chestplate',
  legs: 'legs',
  shield: 'shield',
  feet: 'boots',
  hands: 'gloves',
  ring: 'ring',
  cape: 'cape',
  neck: 'amulet',
  ammo: 'ammo',
};

// --- Metal tiers -------------------------------------------------------------

interface Tier {
  readonly id: string;
  /** Attack level to wield weapons / Defence level to wear armour. */
  readonly combat: number;
  /** Woodcutting level for the axe / Mining level for the pickaxe. */
  readonly tool: number;
  /** Axe and pickaxe power tier. */
  readonly power: number;
}

const TIERS: readonly Tier[] = [
  { id: 'bronze', combat: 1, tool: 1, power: 1 },
  { id: 'iron', combat: 1, tool: 1, power: 2 },
  { id: 'steel', combat: 5, tool: 6, power: 3 },
  { id: 'black', combat: 10, tool: 11, power: 4 },
  { id: 'mithril', combat: 20, tool: 21, power: 5 },
  { id: 'adamant', combat: 30, tool: 31, power: 6 },
  { id: 'rune', combat: 40, tool: 41, power: 7 },
];

const WEAPON_KINDS: ReadonlyArray<readonly [string, WeaponType, string]> = [
  ['dagger', 'dagger', '🗡️'],
  ['sword', 'sword', '⚔️'],
  ['scimitar', 'scimitar', '🗡️'],
  ['longsword', 'longsword', '⚔️'],
  ['mace', 'mace', '🏏'],
  ['warhammer', 'warhammer', '🔨'],
  ['battleaxe', 'battleaxe', '🪓'],
  ['2h_sword', '2h', '⚔️'],
];

const ARMOUR_KINDS: ReadonlyArray<readonly [string, string]> = [
  ['med_helm', '⛑️'],
  ['full_helm', '🪖'],
  ['chainbody', '🎽'],
  ['platebody', '👕'],
  ['platelegs', '👖'],
  ['sq_shield', '🔲'],
  ['kiteshield', '🛡️'],
];

for (const tier of TIERS) {
  const attackReq = tier.combat > 1 ? [{ skill: 'attack' as const, level: tier.combat }] : undefined;
  const defenceReq = tier.combat > 1 ? [{ skill: 'defense' as const, level: tier.combat }] : undefined;
  for (const [kind, weaponType, icon] of WEAPON_KINDS) {
    wiki(`${tier.id}_${kind}`, { icon, weaponType, equipReq: attackReq });
  }
  for (const [kind, icon] of ARMOUR_KINDS) {
    wiki(`${tier.id}_${kind}`, { icon, equipReq: defenceReq });
  }
  wiki(`${tier.id}_axe`, {
    icon: '🪓',
    weaponType: 'axe',
    equipReq: attackReq,
    axeTier: tier.power,
    toolLevel: tier.tool,
  });
  wiki(`${tier.id}_pickaxe`, {
    icon: '⛏️',
    weaponType: 'pickaxe',
    equipReq: attackReq,
    pickTier: tier.power,
    toolLevel: tier.tool,
  });
}

// --- Other equipment -----------------------------------------------------------
wiki('wooden_shield', { icon: '🛡️' });
wiki('leather_boots', { icon: '🥾' });
wiki('leather_gloves', { icon: '🧤' });
wiki('leather_body', { icon: '🧥' });
wiki('leather_chaps', { icon: '👖' });
wiki('leather_cowl', { icon: '🧢' });
wiki('goblin_mail', { icon: '🎽' });
wiki('gold_ring', { icon: '💍' });
wiki('holy_symbol', { icon: '✨' });
wiki('amulet_of_power', { icon: '📿' });
wiki('max_cape', { icon: '🧥', equipReq: [{ skill: 'attack', level: 99 }] });

// --- Currency & remains ----------------------------------------------------------
wiki('coins', { icon: '🪙' });
wiki('bones', { icon: '🦴', buryXp: 4.5 });
wiki('big_bones', { icon: '🦴', buryXp: 15 });
wiki('ashes', { icon: '🌫️' });

// --- Ranged and magic weapons ------------------------------------------------------
wiki('shortbow', { icon: '🏹', weaponType: 'bow', attackRange: 7, ammoKind: 'arrow' });
wiki('bronze_arrow', { icon: '➶', ammoFor: 'arrow' });
wiki('staff_of_air', { icon: '🪄', weaponType: 'staff', staffRunes: ['air_rune'] });

// --- Runes ---------------------------------------------------------------------------
wiki('air_rune', { icon: '🌬️' });
wiki('mind_rune', { icon: '🧠' });
wiki('water_rune', { icon: '💧' });
wiki('earth_rune', { icon: '🟤' });
wiki('fire_rune', { icon: '🔥' });
wiki('body_rune', { icon: '⚪' });

// --- Skilling resources ----------------------------------------------------------
wiki('logs', { icon: '🪵', firemaking: { level: 1, xp: 40 } });
wiki('oak_logs', { icon: '🪵', firemaking: { level: 15, xp: 60 } });
wiki('willow_logs', { icon: '🪵', firemaking: { level: 30, xp: 90 } });
wiki('copper_ore', { icon: '🟠' });
wiki('tin_ore', { icon: '⚪' });
wiki('iron_ore', { icon: '⚫' });
wiki('coal', { icon: '⬛' });
wiki('bronze_bar', { icon: '🟫' });
wiki('iron_bar', { icon: '🔩' });
wiki('steel_bar', { icon: '⬜' });

// --- Tools -----------------------------------------------------------------------
wiki('tinderbox', { icon: '🔥' });
wiki('small_fishing_net', { icon: '🕸️' });
wiki('fishing_rod', { icon: '🎣' });
wiki('fishing_bait', { icon: '🪱' });
wiki('hammer', { icon: '🔨' });
wiki('knife', { icon: '🔪' });

// --- Food & fish -------------------------------------------------------------------
wiki('bread', { icon: '🍞', heals: 5 });
wiki('raw_shrimps', { icon: '🦐', cooking: { cooked: 'shrimps', burnt: 'burnt_shrimps', level: 1, xp: 30, stopBurn: 34, stopBurnRange: 31 } });
wiki('shrimps', { icon: '🍤', heals: 3 });
wiki('raw_anchovies', { icon: '🐟', cooking: { cooked: 'anchovies', burnt: 'burnt_fish', level: 1, xp: 30, stopBurn: 34, stopBurnRange: 31 } });
wiki('anchovies', { icon: '🐟', heals: 1 });
wiki('raw_sardine', { icon: '🐟', cooking: { cooked: 'sardine', burnt: 'burnt_fish', level: 1, xp: 40, stopBurn: 38, stopBurnRange: 34 } });
wiki('sardine', { icon: '🐟', heals: 4 });
wiki('raw_herring', { icon: '🐟', cooking: { cooked: 'herring', burnt: 'burnt_fish', level: 5, xp: 50, stopBurn: 41, stopBurnRange: 38 } });
wiki('herring', { icon: '🐟', heals: 5 });
wiki('raw_trout', { icon: '🐠', cooking: { cooked: 'trout', burnt: 'burnt_fish', level: 15, xp: 70, stopBurn: 49, stopBurnRange: 45 } });
wiki('trout', { icon: '🐠', heals: 7 });
wiki('raw_rat_meat', { icon: '🥩', cooking: { cooked: 'cooked_meat', burnt: 'burnt_meat', level: 1, xp: 30, stopBurn: 34 } });
wiki('cooked_meat', { icon: '🍖', heals: 3 });
wiki('burnt_meat', { icon: '🍂' });
wiki('burnt_shrimps', { icon: '🍂' });
define({ id: 'burnt_fish', name: 'Burnt fish', icon: '🍂', examine: 'Oops!', value: 1, weightKg: 0.2 });

// Kept for older saves and tests that reference the anchovy burn id.
define({ id: 'burnt_anchovies', name: 'Burnt fish', icon: '🍂', examine: 'Oops!', value: 1, weightKg: 0.2 });

/** The attack-style set a weapon exposes, by its id's family name. */
export function weaponTypeOfItem(id: string): WeaponType {
  return ITEMS[id]?.weaponType ?? 'unarmed';
}
